### PR TITLE
ci: stop testing against NodeJS v14, v16

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: Drop support for NodeJS v14, v16

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]

**Review by kfcampbell — APPROVED** [review]
@wolfy1339 is there anything else you'd like to see done before I merge this PR (and similar PRs you've opened in the past)?

**Comment by wolfy1339** [comment]
Not all of theses PRs can be merged. Current beta versions of modules won't affect this module, so this one can be safely merged

**Comment by kfcampbell** [comment]
How are you determining which PRs can/cannot be merged? My tentative plan was go to through the list in "In Review" [here](https://github.com/orgs/octokit/projects/10/views/1?filterQuery=-status%3A%22%F0%9F%86%95+Triage%22%2C%22%F0%9F%94%A5+Backlog%22+ci) and do the merges in that order, which @gr2m organized (thank you!) in an order that will minimize dependency hassles.

**Comment by wolfy1339** [comment]
If a plugin handles routes, or requests, or a plugin extending requests, it will have to wait until the changes for the next major version are complete

**Comment by wolfy1339** [comment]
Basically, anything that might get affected by the work to remove previews for the REST API

**Comment by kfcampbell** [comment]
Hmm...could you help me maybe make a complete list? My best guess is:

| Wait on merging | Okay to merge |
| ------------------------ | -------------------- | 
| https://github.com/octokit/oauth-methods.js/pull/152 | https://github.com/octokit/plugin-enterprise-cloud.js/pull/437 |
| https://github.com/octokit/webhooks-methods.js/pull/157 | https://github.com/octokit/plugin-enterprise-server.js/pull/564 |
| https://github.com/octokit/plugin-paginate-graphql.js/pull/78 | https://github.com/octokit/plugin-request-log.js/pull/321|
| https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/637   | https://github.com/octokit/plugin-create-or-update-text-file.js/pull/154   |
| https://github.com/octokit/auth-callback.js/pull/148  |   |
| https://github.com/octokit/auth-unauthenticated.js/pull/219  |   |
| https://github.com/octokit/auth-token.js/pull/340 |   |
| https://github.com/octokit/auth-action.js/pull/313   |   |
| https://github.com/octokit/auth-oauth-app.js/pull/337   |   |
| https://github.com/octokit/auth-oauth-device.js/pull/143  |    |
|  https://github.com/octokit/auth-oauth-user.js/pull/155 |   |
|  https://github.com/octokit/auth-app.js/pull/477 |   |
|   https://github.com/octokit/webhooks.js/pull/849 |     |
|  https://github.com/octokit/create-octokit-project.js/pull/257  |    |
| https://github.com/octokit/oauth-app.js/pull/414   |    |

But I'm pretty confident I didn't split them correctly.

**Comment by wolfy1339** [comment]
| Merge to Beta                                                        | Okay to Merge                                                    |
| -------------------------------------------------------------------- | ---------------------------------------------------------------- |
| https://github.com/octokit/plugin-rest-endpoint-methods.js/pulls/637 | #152                                                             |
| https://github.com/octokit/plugin-paginate-graphql.js/pulls/78       | https://github.com/octokit/webhooks-methods.js/pulls/157         |
|                                                                      | https://github.com/octokit/auth-callback.js/pulls/148            |
|                                                                      | https://github.com/octokit/auth-unauthenticated.js/pulls/219     |
|                                                                      | https://github.com/octokit/auth-token.js/pulls/340               |
|                                                                      | https://github.com/octokit/auth-action.js/pulls/313              |
|                                                                      | https://github.com/octokit/auth-oauth-app.js/pulls/337           |
|                                                                      | https://github.com/octokit/auth-oauth-device.js/pulls/143        |
|                                                                      | https://github.com/octokit/auth-oauth-user.js/pulls/155          |
|                                                                      | https://github.com/octokit/auth-app.js/pulls/477                 |
|                                                                      | https://github.com/octokit/webhooks.js/pulls/849                 |
|                                                                      | https://github.com/octokit/create-octokit-project.js/pulls/257   |
|                                                                      | https://github.com/octokit/plugin-enterprise-cloud.js/pulls/437  |
|                                                                      | https://github.com/octokit/plugin-enterprise-server.js/pulls/564 |
|                                                                      | https://github.com/octokit/plugin-request-log.js/pulls/321       |

The ones that are listed in the "Merge to Beta" column need to wait for updates from upstream packages to trickle down before they can be merged to stable, as those packages have some breaking changes waiting.

If there is already a `beta` branch with an open PR, merge it there and not `main`

**Comment by kfcampbell** [comment]
Thanks @wolfy1339! I'll go through and knock these out.

**Review by kfcampbell — APPROVED** [review]

**Pull request merged**
